MAX_CONTENT_WIDTH_PX = 760
MAX_CONTENT_WIDTH = f"{MAX_CONTENT_WIDTH_PX}px"

# Shared 3-column layout widths used by templates (label + 2 value cols).
FORM_3COL_LABEL_WIDTH_PX = 120
FORM_3COL_VALUE_WIDTH_PX = (MAX_CONTENT_WIDTH_PX - FORM_3COL_LABEL_WIDTH_PX) // 2
FORM_3COL_LABEL_WIDTH = f"{FORM_3COL_LABEL_WIDTH_PX}px"
FORM_3COL_VALUE_WIDTH = f"{FORM_3COL_VALUE_WIDTH_PX}px"

# Legacy template width values to be normalized to MAX_CONTENT_WIDTH.
LEGACY_CONTENT_WIDTH_PX = 800
LEGACY_CONTENT_WIDTH = f"{LEGACY_CONTENT_WIDTH_PX}px"
